Repository tam-bourine/club-manager, pull requests merged in 2021-03, with the labels that each got.

#191 承認機能結合(全部trueのケースのみ)
  docs/sequence-diagram/CreateClub.pu
  src/api/gas/api.ts
  src/api/kibela/mutations/note.ts
  src/commands/newClub.ts
  src/types/Messages.ts
Labels: Bolt, Kibela

#195 創部申請(ショートカットver.)
  src/commands/newClub.ts
  src/index.ts
  src/shortcuts/newClub.ts
Labels: Bolt

#202 入部処理後のResponseにKibelaUrl等を含める
  src/commands/newClub.ts
  src/config/modalConfig.ts
  src/gas/models/Club/JoinModel.ts
  src/index.ts
  src/modal/modalTemplate.ts
  src/shortcuts/newClub.ts
Labels: GAS

#185 GAS docs 修正
  README.md
Labels: GAS

#192 入部申請モーダル表示コマンド
  nodemon.json
  package-lock.json
  package.json
  src/api/gas/api.ts
  src/blocks/generalComponents.ts
  src/blocks/joinClub.ts
  src/commands/joinClub.ts
  src/commands/newClub.ts
  src/config/clubConfig.ts
  src/config/errorConfig.ts
  src/config/modalConfig.ts
  src/index.ts
  src/modal/modalTemplate.ts
  src/shortcuts/newClub.ts
  src/types/Messages.ts
Labels: Bolt

#215 定数の個別exportの廃止
  src/blocks/inputClub.ts
  src/blocks/joinClub.ts
  src/blocks/messages/modal.ts
  src/blocks/reject.ts
  src/commands/joinClub.ts
  src/commands/newClub.ts
  src/config/clubConfig.ts
  src/config/errorConfig.ts
  src/config/modalConfig.ts
  src/modal/modalTemplate.ts
  src/shortcuts/newClub.ts
Labels: Bolt

#256 Actions で lint するタイミングの修正
  .github/workflows/lint.yml
Labels: common

#194 入部モーダルで申請後の処理
  docs/gas_api/OpenApi.json
  package.json
  src/api/gas/api.ts
  src/api/kibela/api.ts
  src/api/kibela/mutations/note.ts
  src/api/kibela/queries/group.ts
  src/api/kibela/queries/note.ts
  src/api/kibela/queries/user.ts
  src/blocks/generalComponents.ts
  src/commands/newClub.ts
  src/config/errorConfig.ts
  src/gas/models/Club/ApproveModel.ts
  src/gas/models/Club/JoinModel.ts
  src/gas/models/Clubs/GetModel.ts
  src/gas/shared/Constants.ts
  src/gas/shared/types/ApproveInterface.ts
  src/gas/shared/types/JoinInterface.ts
  src/gas/shared/types/ResponseInterface.ts
  src/modal/modalTemplate.ts
  src/shortcuts/joinClub.ts
  src/types/Messages.ts
  src/types/slack/User.ts
Labels: Bolt, Kibela

#262 mainで`trigger_id` expiredと出て入部処理が落ちる問題の修正
  src/commands/newClub.ts
  src/index.ts
  src/shortcuts/joinClub.ts
  src/shortcuts/newClub.ts
Labels: Bolt, bug, hotfix

#266 Cloud Buildでメモリオーバーしてしまう問題を解決(したい)
  .firebaserc
  .gcloudignore
  firebase.json
Labels: bug
