Repository tam-bourine/club-manager, pull requests merged in 2021-02, with the labels that each got.

#106 ショートカットを用いた創部申請
  .eslintignore
  .eslintrc.json
  package-lock.json
  package.json
  src/functions/blocks/clubInfo.ts
  src/functions/blocks/generalComponent.ts
  src/functions/blocks/inputClub.ts
  src/functions/clubConfig.ts
  src/functions/commands/newClub.ts
  src/functions/config.json.example
  src/functions/index.ts
  src/functions/types/getMessage.ts
  src/functions/workflowStep/addClub.ts
  webpack.config.js
Labels: feat

#119 BlockKit用関数Labelの内包化
  package.json
  src/functions/blocks/clubInfo.ts
  src/functions/blocks/generalComponent.ts
  src/functions/blocks/generalComponents.ts
  src/functions/blocks/messages/modal.ts
  src/functions/commands/newClub.ts
  src/functions/types/Messages.ts
Labels: Bolt

#132 SocketModeでの開発方法の資料を追加
  README.md
Labels: Bolt, environment

#136 Lint バグ やっと直ったぞ〜
  package.json
  src/functions/blocks/messages/modal.ts
  src/functions/commands/newClub.ts
  src/gas/controllers/InvalidActionController.ts
  src/gas/models/Club/ApproveModel.ts
  src/gas/models/Club/RegistModel.ts
  src/gas/models/Clubs/GetModel.ts
  src/gas/routes.ts
  src/gas/shared/Response.ts
Labels: bug

#137 Kibela API 連携
  .env.example
  @types/kibela.d.ts
  codegen.js
  package-lock.json
  package.json
  src/functions/api/index.ts
  src/functions/api/kibela.ts
  src/functions/index.ts
  src/functions/kibela/constants.ts
  src/functions/kibela/mutations/note.ts
  src/functions/kibela/mutations/user.ts
  src/functions/kibela/queries/group.ts
  src/functions/kibela/queries/note.ts
  src/functions/kibela/queries/user.ts
  src/kibela/addMemberToGroup.ts
  src/kibela/constants.ts
  src/kibela/fetchUserByEmail.ts
  tsconfig.json
Labels: Kibela

#127 承認モーダル
  .gitignore
  firebase.json
  package-lock.json
  package.json
  src/functions/blocks/approval.ts
  src/functions/blocks/generalComponents.ts
  src/functions/blocks/inputClub.ts
  src/functions/blocks/messages/modal.ts
  src/functions/blocks/reject.ts
  src/functions/commands/newClub.ts
  src/functions/config.json.example
  src/functions/config/clubConfig.ts
  src/functions/config/modalConfig.ts
  src/functions/modal/modalTemplate.ts
  src/functions/types/Messages.ts
Labels: Bolt

#140 ts-node-devを入れたい
  package-lock.json
  package.json
Labels: Bolt, environment

#142 kibelaAPIにてemailからuserを検索する関数
  src/functions/kibela/queries/user.ts
Labels: Kibela

#152 創部申請モーダルの項目変更
  src/functions/blocks/inputClub.ts
  src/functions/blocks/messages/modal.ts
  src/functions/commands/newClub.ts
  src/functions/config/clubConfig.ts
  src/functions/types/Messages.ts
Labels: Bolt

#149 GAS POST approve 時にシート作成・メンバー追加
  docs/gas_api/OpenApi.json
  src/gas/controllers/Club/ApproveController.ts
  src/gas/models/Club/ApproveModel.ts
  src/gas/shared/Constants.ts
  src/gas/shared/types/ApproveInterface.ts
  src/gas/shared/types/UtilityTypes.ts
Labels: GAS

#156 kibelaユーザーを部活グループに入れる
  src/functions/kibela/mutations/note.ts
  src/functions/kibela/mutations/user.ts
  src/functions/kibela/queries/group.ts
  src/functions/kibela/queries/note.ts
  src/functions/kibela/queries/user.ts
Labels: Kibela

#151 SlackユーザーIDからemail等を取得
  src/functions/api/kibela/index.ts
  src/functions/api/kibela/mutations/note.ts
  src/functions/api/kibela/mutations/user.ts
  src/functions/api/kibela/queries/group.ts
  src/functions/api/kibela/queries/note.ts
  src/functions/api/kibela/queries/user.ts
  src/functions/api/slack/index.ts
  src/functions/api/slack/user.ts
  src/functions/index.ts
  src/functions/types/slack/User.ts
Labels: Bolt, feat

#172 Firebase -> GCR
  .gcloudignore
  package-lock.json
  package.json
  src/api/kibela/index.ts
  src/api/kibela/kibela/index.ts
  src/api/kibela/kibela/mutations/note.ts
  src/api/kibela/kibela/mutations/user.ts
  src/api/kibela/kibela/queries/group.ts
  src/api/kibela/kibela/queries/note.ts
  src/api/kibela/kibela/queries/user.ts
  src/api/kibela/mutations/note.ts
  src/api/kibela/mutations/user.ts
  src/api/kibela/queries/group.ts
  src/api/kibela/queries/note.ts
  src/api/kibela/queries/user.ts
  src/api/kibela/slack/index.ts
  src/api/kibela/slack/user.ts
  src/api/slack/index.ts
  src/api/slack/user.ts
  src/blocks/approval.ts
  src/blocks/generalComponents.ts
  src/blocks/inputClub.ts
  src/blocks/messages/modal.ts
  src/blocks/reject.ts
  src/commands/newClub.ts
  src/config/clubConfig.ts
  src/config/modalConfig.ts
  src/constant.ts
  src/gas/models/Club/RegistModel.ts
  src/index.ts
  src/modal/modalTemplate.ts
  src/types/Messages.ts
  src/types/slack/User.ts
Labels: Bolt, Kibela, Refactoring, environment

#173 fix: 🐛 remain functions
  package.json
  tsconfig.json
Labels: Bolt, GAS, Kibela, bug, common, environment

#175 fix: 🐛 gcloudignore
  .gcloudignore
Labels: Bolt, Kibela, Refactoring, bug, common, environment, feat

#179 fix: 🐛 remain process.env.PORT
  src/constant.ts
  src/index.ts
Labels: Bolt, Kibela, Refactoring, common, environment

#167 承認ボタンを押してモーダル表示からイベント発火まで
  package-lock.json
  package.json
  src/api/kibela/api.ts
  src/api/kibela/index.ts
  src/api/kibela/kibela/mutations/note.ts
  src/api/kibela/kibela/mutations/user.ts
  src/api/kibela/kibela/queries/group.ts
  src/api/kibela/kibela/queries/note.ts
  src/api/kibela/kibela/queries/user.ts
  src/api/kibela/mutations/index.ts
  src/api/kibela/mutations/note.ts
  src/api/kibela/mutations/user.ts
  src/api/kibela/queries/group.ts
  src/api/kibela/queries/index.ts
  src/api/kibela/queries/note.ts
  src/api/kibela/queries/user.ts
  src/api/kibela/slack/user.ts
  src/api/slack/user.ts
  src/blocks/approval.ts
  src/blocks/generalComponents.ts
  src/commands/newClub.ts
  src/types/Messages.ts
Labels: Bolt

#182 GAS創部承認 レスポンス修正
  docs/gas_api/OpenApi.json
  src/gas/models/Club/ApproveModel.ts
  src/gas/shared/Constants.ts
  src/gas/shared/types/ResponseInterface.ts
Labels: GAS

#184 創部申請情報をGASにPOSTする処理
  .env.example
  src/api/gas/api.ts
  src/api/gas/index.ts
  src/commands/newClub.ts
  src/config/clubConfig.ts
  src/constant.ts
  src/types/Messages.ts
  src/types/slack/User.ts
Labels: Bolt, feat
